/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegisterRouteImport } from './routes/app.register'
import { Route as AppPayRouteImport } from './routes/app.pay'
import { Route as AppCertificateRouteImport } from './routes/app.certificate'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppPayRoute = AppPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificateRoute = AppCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/app/pay': typeof AppPayRoute
  '/app/register': typeof AppRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/app/pay': typeof AppPayRoute
  '/app/register': typeof AppRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/app/pay': typeof AppPayRoute
  '/app/register': typeof AppRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/verify'
    | '/app/certificate'
    | '/app/pay'
    | '/app/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/verify'
    | '/app/certificate'
    | '/app/pay'
    | '/app/register'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/verify'
    | '/app/certificate'
    | '/app/pay'
    | '/app/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pay': {
      id: '/app/pay'
      path: '/pay'
      fullPath: '/app/pay'
      preLoaderRoute: typeof AppPayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificate': {
      id: '/app/certificate'
      path: '/certificate'
      fullPath: '/app/certificate'
      preLoaderRoute: typeof AppCertificateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCertificateRoute: typeof AppCertificateRoute
  AppPayRoute: typeof AppPayRoute
  AppRegisterRoute: typeof AppRegisterRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCertificateRoute: AppCertificateRoute,
  AppPayRoute: AppPayRoute,
  AppRegisterRoute: AppRegisterRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
