/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminBlogRouteImport } from './routes/admin-blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppCertificateRouteImport } from './routes/app.certificate'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin-blog',
  path: '/admin-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificateRoute = AppCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-blog': typeof AdminBlogRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-blog': typeof AdminBlogRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-blog': typeof AdminBlogRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/app/certificate': typeof AppCertificateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-blog'
    | '/app'
    | '/help'
    | '/login'
    | '/messages'
    | '/pay'
    | '/payments'
    | '/profile'
    | '/register'
    | '/registry'
    | '/verify'
    | '/app/certificate'
    | '/blog/$slug'
    | '/sitemap/xml'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-blog'
    | '/app'
    | '/help'
    | '/login'
    | '/messages'
    | '/pay'
    | '/payments'
    | '/profile'
    | '/register'
    | '/registry'
    | '/verify'
    | '/app/certificate'
    | '/blog/$slug'
    | '/sitemap/xml'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-blog'
    | '/app'
    | '/help'
    | '/login'
    | '/messages'
    | '/pay'
    | '/payments'
    | '/profile'
    | '/register'
    | '/registry'
    | '/verify'
    | '/app/certificate'
    | '/blog/$slug'
    | '/sitemap/xml'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PayRoute: typeof PayRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegistryRoute: typeof RegistryRoute
  VerifyRoute: typeof VerifyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-blog': {
      id: '/admin-blog'
      path: '/admin-blog'
      fullPath: '/admin-blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificate': {
      id: '/app/certificate'
      path: '/certificate'
      fullPath: '/app/certificate'
      preLoaderRoute: typeof AppCertificateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCertificateRoute: typeof AppCertificateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCertificateRoute: AppCertificateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminBlogRoute: AdminBlogRoute,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PayRoute: PayRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegistryRoute: RegistryRoute,
  VerifyRoute: VerifyRoute,
  BlogSlugRoute: BlogSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
