REVOKE EXECUTE ON FUNCTION public.claim_first_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.grant_admin(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.revoke_admin(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.list_admins() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_member_status(uuid, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.claim_first_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_admins() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_member_status(uuid, text) TO authenticated;